[package]
name = "packages_crates_modules"
version = "0.1.0"
authors = ["tanveerahmed"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
library_01 = {path = "library_01"}
