[package]
name = "generics_traits_lifetime"
version = "0.1.0"
authors = ["TanveerAhmed98 <tanveer.ahm98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
